kafka:
  bootstrap-servers: "kafka:29092"
  group_id_config: "sample-group"
  schema-registry-url: "http://schemaregistry:8081"
  message-for-product-ms-topic: message-for-product-ms-topic
  response-for-user-topic: response-for-user-topic
